// Automatically generated by astro-icon
// b3cd7884f493322a9d12d9093bfa0503646d144b0c2faab0ba05b66894661bf4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "anchor"
		| "arrow-down"
		| "arrow-up-right"
		| "book-open-search"
		| "chart-line"
		| "chart-pie"
		| "component"
		| "email"
		| "hamburger"
		| "help-square"
		| "layers"
		| "messages"
		| "meta"
		| "microscope"
		| "minus"
		| "moneytree"
		| "origami"
		| "palette"
		| "people"
		| "person"
		| "person-circle"
		| "plus"
		| "projector-board"
		| "puzzle-piece"
		| "rainforestqa"
		| "resn"
		| "smiley-happy"
		| "sparkles"
		| "xero";
}