// Automatically generated by astro-icon
// 85a7d95c236f192147741aec5add3ef57fcfd10fadc3579f23b1e94dd80cd6a0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "anchor"
		| "chart-pie"
		| "component"
		| "help-square"
		| "layers"
		| "microscope"
		| "minus"
		| "palette"
		| "person-circle"
		| "plus"
		| "projector-board"
		| "puzzle-piece";
}