// Automatically generated by astro-icon
// e3fa32a8e1e569627ae7a61ec91a16cd14ef1078a3c9a8b4bd8db7b86ca49d6a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "anchor"
		| "chart-pie"
		| "component"
		| "help-square"
		| "layers"
		| "microscope"
		| "palette"
		| "person-circle"
		| "projector-board"
		| "puzzle-piece";
}